query SelectedLocalGroups {
  selectedLocalGroups @client
}

query SelectedWorkingGroups {
  selectedWorkingGroups @client
}

query SelectedTimeCommitment {
  selectedTimeCommitment @client
}

query RoleAmount {
  roleAmount @client
}

query SearchString {
  searchString @client
}

query Filters @client {
  searchString
  selectedLocalGroups
  selectedWorkingGroups
  selectedTimeCommitment
}

query NavbarHeight {
  navbarHeight @client
}

query LocalGroupById($id: Int!) {
  localGroupById(id: $id) @client {
    id
    name
  }
}

mutation UpdateLocalGroups($names: [String!]) {
  updateLocalGroups(names: $names) @client
}

mutation UpdateWorkingGroups($names: [String!]) {
  updateWorkingGroups(names: $names) @client
}

mutation UpdateTimeCommitmentRange($range: [Int!]) {
  updateTimeCommitmentRange(range: $range) @client
}

mutation UpdateRoleAmount($amount: [Int!]) {
  updateRoleAmount(amount: $amount) @client
}
