query local_group {
  __typename
  local_group {
    id
    name
  }
}

mutation insert_localgroup($objects: [local_group_insert_input!]!) {
  insert_local_group(objects: $objects) {
    returning {
      id
      name
    }
  }
}

query working_group {
  __typename
  working_group {
    id
    name
  }
}

query role {
  __typename
  role {
    id
    name
    local_group {
      id
      name
    }
    working_group {
      id
      name
    }
    location
    time_commitment
  }
}
