query localGroup {
  __typename
  local_group {
    id
    name
  }
}

mutation insertLocalGroup($objects: [local_group_insert_input!]!) {
  insert_local_group(objects: $objects) {
    returning {
      id
      name
    }
  }
}

query workingGroup {
  __typename
  working_group {
    id
    name
  }
}

query role {
  __typename
  role {
    id
    name
    local_group {
      id
      name
    }
    working_group {
      id
      name
    }
    location
    time_commitment
  }

}

query timeCommitment {
  role_aggregate {
    aggregate {
      min {
        time_commitment_min
      }
      max {
        time_commitment_max
      }
    }
  }
}

type FilterEqInt {
  _eq: Int!
}

type FilterRoles {
  localGroups: FilterEqInt
  workingGroups: FilterEqInt
}
