version: '3.6'
services:
  frontend:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "graphql-engine"

volumes:
  db_data:
