fragment roleFields on role {
  id
  title
  responsibilities
  description
  requirements
  timeCommitmentMin
  timeCommitmentMax
  email
  mattermostId
  phone
  createdDate
  dueDate
  workingCircle {
    title
    id
  }
  localGroup {
    title
    id
  }
}

query RolesQuery($limit: Int!, $offset: Int!) {
  roles(order_by: { createdDate: desc }, limit: $limit, offset: $offset) {
    ...roleFields
  }
}
