name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Cache dependencies so they can be reused by following jobs
      - uses: actions/cache@v2
        # Use this to check for `cache-hit` below
        id: npm-cache
        with:
          path: node_modules
          # Bust cache when we update dependencies
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      # Only install dependencies when not found in cache
      - uses: actions/setup-node@v1
        if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          node-version: '12'
      - run: npm ci
        if: steps.npm-cache.outputs.cache-hit != 'true'
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Use cached dependencies
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm run lint
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm run build
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm run test:unit
  i18n-push:
    # Only run this on commits to master
    if: ${{ github.event_name == 'push' }}
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm run i18n:push
        env:
          LOCO_API_KEY: ${{ secrets.LOCO_API_KEY }}